// This file is generated by Velite

import type __vc from '../../../../velite.config.ts';

type Collections = typeof __vc.collections;

export type Image = Collections['image']['schema']['_output'];
export declare const image: Image[];

export type Link = Collections['link']['schema']['_output'];
export declare const link: Link[];

export type Card = Collections['card']['schema']['_output'];
export declare const card: Card[];

export type Cover = Collections['cover']['schema']['_output'];
export declare const cover: Cover[];

export type Team = Collections['team']['schema']['_output'];
export declare const team: Team[];

export type Places = Collections['places']['schema']['_output'];
export declare const places: Places[];

export type Home = Collections['home']['schema']['_output'];
export declare const home: Home;

export type Courses = Collections['courses']['schema']['_output'];
export declare const courses: Courses;

export type Booking = Collections['booking']['schema']['_output'];
export declare const booking: Booking;

export type Pricelist = Collections['pricelist']['schema']['_output'];
export declare const pricelist: Pricelist;

export type About = Collections['about']['schema']['_output'];
export declare const about: About;

export type Editor = Collections['editor']['schema']['_output'];
export declare const editor: Editor;
